#!/bin/bash

# init
function init() {
    echo "==========================="
    echo "= START COMPILING KERNEL  ="
    echo "==========================="
}
# Main 
function compile() {
    make -j$(nproc --all) O=out ARCH=arm64 RMX2185_defconfig
    make -j$(nproc --all) ARCH=arm64 O=out \
                          CROSS_COMPILE=aarch64-linux-gnu- \
                          CROSS_COMPILE_ARM32=arm-linux-gnueabi-
}
#end
function end(){
    echo "==========================="
    echo "  COMPILE KERNEL COMPLETE  "
    echo "==========================="
}

# execute
init
compile
end
